### PR TITLE
Specify filesystem on disk image creation

### PR DESCRIPTION
**Pull request by orbsmiv**
DMG filesystem fix for issues #101 #100

### CODE REVIEW

**Comment by npfister13** [comment]
Thanks for this, but how do I go about implementing this fix? 
I've also considered just using 2.14.x as some users say it works, but I'm also not entirely sure how to install that either.

**Comment by orbsmiv** [comment]
@npfister13 if you wanted to implement this immediately you'd need to build the installer using the makefile but make sure that you include the changes that I've proposed. If the developer merges my pull request then future releases will produce an HFS+ dmg file, rather than APFS.

All of the builds of git_osx_installer are available here: https://sourceforge.net/projects/git-osx-installer/files/

**Comment by clburlison** [comment]
Any chance this can get merged and a new release made? This affects all of my machines not running 10.13 and while I'd love to say all of my fleet is on 10.13 that currently isn't the case.

**Comment by orbsmiv** [comment]
Just gently bumping this PR!

**Comment by rigobauer** [comment]
Any reason to not merging this? Current installer doesn't work in "El Capitan"...

**Comment by yamsellem** [comment]
I've just lost 45 minutes to understand that git 2.15 install does not work on El Capitan with Case-insensitive APFS. Git is one of the first thing to install after a fresh OSX install, so, at first, I was thinking [the file system was broken or something](https://www.jamf.com/jamf-nation/discussions/17759/no-mountable-filesystems-cant-mount-any-dmg); as it seems to be a known issue on El Capitan.

May you please take a closer look at this PR?
It will be a great help.

_ps. to solve this, I've installed [a 2.14.1 git release](https://sourceforge.net/projects/git-osx-installer/files/) which works fine_

**Comment by orbsmiv** [comment]
Another gentle bump!

**Comment by timcharper** [comment]
Thanks for bringing this to my attention; I get way too many GitHub notifications and had missed this thread :'( and was blissfully unaware. Merged and 2.15.1 released. Sorry for the delay!

**Comment by erikng** [comment]
Thanks @timcharper - for everyone following, you can find that build at the following url:

https://sourceforge.net/projects/git-osx-installer/files/git-2.15.1-intel-universal-mavericks.dmg/download

**Pull request merged**
