### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Danx0626**

### CODE REVIEW

**Comment by chokbantaa** [comment]
D

**Comment by timcharper** [comment]
Not sure what this is but it's old and I universal support is already added.

**Comment by Aslme** [comment]
https://opencollective.com/api/connected-accounts/github/callback?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkhTMjU2LTIwMTktMDktMDIifQ.eyJpYXQiOjE1ODk5NDc1NTEsImV4cCI6MTU5NzcyMzU1MSwic3ViIjoiMTAzMzY0In0.iPPg2X71Sa1rl-FtngydhcipUBbVHgnt9G8bG42lLOM&redirect=https://opencollective.com/create/opensource&code=1630cff203781dd61a73

**Comment by Frenk8585** [comment]
> _No description provided._

**Pull request closed without merging**
