### PR TITLE
Ask git to create symlinks instead of converting hardlinks to symlinks

### PR DESCRIPTION
**Pull request by SyntevoAlex**
git's Makefile supports creating symlinks since 2.18.0, with commit:
  ad874608 by Ævar Arnfjörð Bjarmason, 2018-03-13 23:39:35
  Makefile: optionally symlink libexec/git-core binaries to bin/git

### CODE REVIEW

**Review by caniso — CHANGES_REQUESTED** [review]
#180

**Comment by homo-programmatis** [comment]
@caniso  Was this comment made by mistake? I don't understand what you meant

**Review by timcharper — APPROVED** [review]

**Comment by timcharper** [comment]
Thank you!

**Comment by SyntevoAlex** [comment]
Thanks for this repo!

**Pull request merged**
